# Generated by Django 4.0.3 on 2022-05-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product_gallery', 'verbose_name_plural': 'product_galleries'},
        ),
    ]
